<?php
function headerMod()
{
    $prefix = "/_Projects/mcmaps-full/";
    echo '<header class="header">';
    echo '<a href="../index.php" class="nav-logo"><img src="../img/logo.png" alt="logo"></a>';
    echo '<nav class="navbar">';
    echo '<ul class="nav-menu">';
    echo '<li class="nav-item">';
    echo '<a href="' . $prefix . 'index.php" class="nav-link">Latest </a>';
    echo '</li>';
    echo '<li class="nav-item">';
    echo '<span class="nav-link">';
    echo 'Map Categories <i class="fa fa-chevron-down"></i>';
    echo '<span class="dropdown">';
    echo '<a href="all-maps.php" class="nav-link">All Maps</a>';
    echo '<a href="puzzle.php" class="nav-link">Puzzle</a>';
    echo '<a href="parkour.php" class="nav-link">Parkour</a>';
    echo '<a href="minigames.php" class="nav-link">Minigames</a>';
    echo '<a href="maze.php" class="nav-link">Maze</a>';
    echo '<a href="pvp.php" class="nav-link">PvP</a>';
    echo '<a href="horror.php" class="nav-link">Horror</a>';
    echo '<a href="other.php" class="nav-link">Other</a>';
    echo '</span>';
    echo '</span>';
    echo '</li>';
    echo '<li class="nav-item">';
    echo '<a href="map-jam.php" class="nav-link">Map Jam</a>';
    echo '</li>';
    echo '<li class="nav-item">';
    echo '<a href="verified.php" class="nav-link">Verified</a>';
    echo '</li>';
    echo '<li class="nav-item">';
    echo '<span class="nav-link">';
    echo 'Other <i class="fa fa-chevron-down"></i>';
    echo '<span class="dropdown">';
    echo '<a href="upload-a-map.php" class="nav-link">Upload a Map</a>';
    echo '<a href="update-a-map.php" class="nav-link">Update a Map</a>';
    echo '</span>';
    echo '</span>';
    echo '</li>';
    echo '<li class="nav-item">';
    echo '<a href="search.php" class="nav-link">Search</a>';
    echo '</li>';
    echo '</ul>';
    echo '<div class="hamburger">';
    echo '<span class="bar"></span>';
    echo '<span class="bar"></span>';
    echo '<span class="bar"></span>';
    echo '</div>';
    echo '</nav>';
    echo '</header>';
}